#!/bin/bash -e

V_MINOR=1
V_PATCH=2

TAG_PREFIX=v
REMOTE=origin

DEBPACKAGE=package

getVersion() {
  cat version
}

setVersion() {
  local version=$1
  echo $version > version
}

nextVersion() {
  local version=$1
  local index=$2
  local IFS=.
  local nums=($version)
  local len=${#nums[@]}
  (( nums[index]++ ))
  while (( ++index < len )); do
    (( nums[index] = 0 ))
  done
  echo "${nums[*]}"
}

getTagId() {
  local version=$1
  git ls-remote --tags $REMOTE "${TAG_PREFIX}${version}" \
    | awk '{print $1}'
}

listTags() {
  git ls-remote --tags $REMOTE "${TAG_PREFIX}*" \
    | awk '{print $2}' \
    | sed 's/^refs\/tags\///'
}

catAdd() {
  cat -
  echo "$@"
}

prevTag() {
  local version=$1
  local tag="${TAG_PREFIX}${version}"
  listTags \
    | catAdd "$tag" \
    | sort -Vur \
    | grep -m 1 -A 1 -xF "$tag" \
    | tail -n +2
}

tailAfter() {
  local value=$1
  local line=""
  while read line && [ "$line" != "$value" ]; do
    true ## Doing nothing
  done
  while read line; do
    echo $line
  done
}

filterSeries() {
  local line=""
  if ! read line; then
    return
  fi
  echo $line
  local pattern="${line%.[0-9]}.[0-9]"
  while read line && [[ "$line" = $pattern ]]; do
    echo $line
  done
}

prevSeries() {
  local version=$1
  local tag="${TAG_PREFIX}${version}"
  listTags \
    | catAdd "$tag" \
    | sort -Vur \
    | tailAfter "$tag" \
    | filterSeries
}

fetchChangelog() {
  local version=$1
  local series=($(prevSeries $version))
  local filter=${series[1]:+${series[0]}}
  local shallow=${series[0]:+${series[-1]}}

  local head=$(git log -1 --format=%H)
  # echo 1>&2 "Fetching commits from ${shallow:-"begin"} to ${head}"
  git fetch --progress ${shallow:+"--shallow-exclude=${shallow}"} \
    $REMOTE $head:changelog \
    ${filter:+"refs/tags/${filter}:refs/tags/${filter}"}
  # echo 1>&2 "Filtering commits from ${filter:-"begin"} to ${head}"
  git log --first-parent --format=%H ${filter:+"${filter}.."}changelog --
}

shortlog() {
  local glp='git log --stdin --no-walk=unsorted --format=%H'
  $glp --author='^(?!frabot)' -P \
    | $glp --invert-grep --grep='Merge( remote-tracking)? branch' -E \
    | $glp --format=tformat:%s
}

changelogEntry() {
  local version=$1
  echo "${DEBPACKAGE} (${version}) unstable; urgency=medium"
  echo
  sed 's/^/  * /'
  echo
  echo " -- ${DEBFULLNAME} <${DEBEMAIL}>  $(date -R)"
  echo
}

updateVersion() {
  local index=$1
  local version=$(getVersion)
  if [ -n "$(getTagId $version)" ]; then
    echo "Increasing version at position ${index}"
    version=$(nextVersion $version $index)
    echo "Setting project version: ${version}"
    setVersion $version
    git add version
  else
    echo "Using project version: ${version}"
  fi
}

updateChangelog() {
  local version=$(getVersion)
  fetchChangelog $version \
    | shortlog \
    | changelogEntry $version \
    | cat - debian/changelog > debian/changelog.new
  mv debian/changelog.new debian/changelog
  git add debian/changelog
}

createTag() {
  local version=$(getVersion)
  git commit -m "Version: ${version}" || true
  git tag "${TAG_PREFIX}${version}"
  git push --tags
  git push
}

setDebIdentity() {
  export DEBFULLNAME="Fra Goi"
  export DEBEMAIL="fragoidev@gmail.com"
}

setGitIdentity() {
  git config user.name frabot
  git config user.email fragoidev@gmail.com
}

createRelease() {
  updateVersion $V_PATCH

  setDebIdentity
  updateChangelog

  setGitIdentity
  createTag
}

resolveVersionConflict() {
  local vv=$(git ls-files -u version | wc -l)
  if [ "$vv" = "3" ]; then
    echo "Restore version file from HEAD"
    git restore --ours version
    git add version
    sed 's/\t/  /g' .git/MERGE_MSG \
      | git commit -F -
  else
    git merge --abort
    return 1
  fi
}

updateBranch() {
  local other=$1
  local current=$(git branch --show-current)
  echo "Merging branch ${other} into ${current}"
  git pull --progress --ff $REMOTE $other || resolveVersionConflict
}

shallowFetch() {
  local branch=$1
  local exclude=$2
  git fetch --progress --shallow-exclude=$exclude $REMOTE $branch && git gc
}

shallowMerge() {
  local branch=$1
  local into=$2

  if [ -z "$into" ]; then
    into=$(git branch --show-current)
  fi

  echo "Merging branch ${branch} into ${into}"

  ## Fetch minimal history from both branches
  shallowFetch $branch $into || true
  shallowFetch $into $branch || true
  git fetch --progress --deepen=1 $REMOTE $branch $into

  git checkout $into
  git merge $REMOTE/$branch || resolveVersionConflict
}

updateDev() {
  local branch=$1
  local into=$2

  setGitIdentity
  # updateBranch $branch
  shallowMerge $branch $into

  updateVersion $V_MINOR

  local version=$(getVersion)
  git commit -m "Next development version: ${version}" || true
  git push
}

# updateDev() {
#   local version=$(getVersion)

#   if [ -n $(getTagId $version) ]; then
#     echo "Nothing to do"
#     return
#   fi

#   echo "Merging release: ${version}"
#   git pull --progress --ff $REMOTE "${TAG_PREFIX}${version}" || true

#   version=$(nextVersion $version $V_MINOR)
#   echo "Setting project version: ${version}"
#   setVersion $version

#   setGitIdentity
#   git commit -am "Next version: ${version}"
#   git push
# }
